In [10]:
import numpy as np

In [15]:
v = np.random.randint(0, 10,size=(5,2))
v

array([[2, 7],
       [7, 7],
       [9, 3],
       [7, 1],
       [6, 2]])

In [28]:
new_v = np.array([])
for i in range(len(v)):
    if i % 2 == 1:
        print(i)
        print(v[i])
        new_v = np.append(new_v, [v[i]])

print(new_v)

1
[7 7]
3
[7 1]
[7. 7. 7. 1.]


In [30]:
reverse_v = np.flip(v)
reverse_v

array([[2, 6],
       [1, 7],
       [3, 9],
       [7, 7],
       [7, 2]])

In [31]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])

200


In [33]:
m = np.random.randint(0, 10,size=(5,5))
m

array([[9, 7, 7, 8, 1],
       [6, 7, 9, 1, 4],
       [9, 7, 0, 7, 9],
       [4, 8, 7, 5, 3],
       [7, 5, 4, 2, 1]])

In [40]:
for i, row in enumerate(m):
    m[i] = np.flip(row)

m

array([[9, 7, 7, 8, 1],
       [6, 7, 9, 1, 4],
       [9, 7, 0, 7, 9],
       [4, 8, 7, 5, 3],
       [7, 5, 4, 2, 1]])

In [41]:
m = m[1:len(m)-1]
m

array([[6, 7, 9, 1, 4],
       [9, 7, 0, 7, 9],
       [4, 8, 7, 5, 3]])

In [43]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr_2d[0][0])
print(arr_2d[0][1])


1
2


In [44]:
print(arr_2d[3][1])
print(arr_2d[3][2])


11
12


In [45]:
print(arr_2d[2][1])

8


In [53]:
a = np.arange(12)
a = a +1
a = a.reshape([4,3])


In [54]:
a.reshape([3,4])


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
b = np.arange(10)

b.reshape((-1,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
c = np.random.randint(0, 10,size=(3,4))
c.reshape((-1))

array([8, 3, 9, 5, 0, 4, 3, 0, 9, 6, 8, 0])

In [73]:
d = np.arange(27)
d = d +1
d.reshape((3,3,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [76]:
e = np.random.randint(0, 10,size=(6,6))
e.reshape((3,12))

array([[7, 8, 2, 5, 8, 1, 2, 2, 2, 1, 5, 2],
       [7, 0, 0, 4, 4, 5, 1, 4, 9, 1, 3, 3],
       [6, 1, 3, 7, 4, 0, 5, 4, 8, 5, 7, 5]])

In [79]:
f = np.random.randint(0, 10,size=(4,4))
f.reshape((16,1))
f.reshape((1,16))


array([[6, 9, 0, 0, 4, 2, 2, 7, 5, 4, 4, 2, 4, 2, 4, 7]])

In [89]:
g = np.random.randint(0, 10,size=(5,6))
g.reshape((-1,2,5))

array([[[1, 2, 5, 9, 4],
        [1, 8, 1, 8, 9]],

       [[1, 0, 2, 6, 3],
        [2, 4, 1, 2, 0]],

       [[7, 9, 5, 9, 7],
        [6, 3, 1, 4, 0]]])

In [90]:
h = np.arange(125)
h.reshape((5,5,5))

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])